### ISSUE TITLE
Large cypher queries

### ISSUE THREAD

**Issue by beaniekun** [niklassaers/theo-example#2]
So I can get small response cypher queries to load fine, but I'm running into an issue with larger requests.
When a large request is made, the app stalls and flags line 123 in connection.swift in the bolt protocol pod. 
The error is "Thread 1: Fatal error list index out of range". The list it is attempting to access by index is the responseData. Any idea why this is happening?

Further testing has shown me that the error will not occur all of the time for a specific requests, leading me to believe the fault is in the bolt server response rather than on the swift side... Has theo been tested with large data responses?

**Comment by beaniekun** [comment]
Discovered the issue was the file installed via cocoapods. The connection.swift had errors, replaced with github version and fault went away.

**Comment by niklassaers** [comment]
Hi Sai,
thanks for reporting, and sorry for not getting back to you sooner. Indeed, as you discovered, the issue was solved about a week ago. Thanks for reminding me I have to update CocoaPods :-)

Cheers

   Niklas
